services:
  - type: web
    name: skylark-web
    env: docker
    dockerfilePath: ./Dockerfile.production
    dockerContext: .
    dockerCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: skylark-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: skylark-redis
          property: connectionString
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
    healthCheckPath: /health
    autoDeploy: true
    buildCommand: echo "Using Dockerfile"
    startCommand: echo "Using Dockerfile"

  - type: redis
    name: skylark-redis
    plan: free
    maxmemoryPolicy: allkeys-lru

databases:
  - name: skylark-db
    databaseName: skylark_production
    user: skylark
    plan: free 